name: Update README Trophy

on:
  # allows to manually run the job at any time
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6

      - name: Prepare output directory
        run: mkdir -p profile

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          options: username=${{ github.repository_owner }}&hide_title=false&layout=compact&card_width=320&langs_count=6&theme=transparent&hide_border=false&locale=en
          file: profile/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Push the generated SVG to the output branch
      - name: push trophy.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v5.0.0
        with:
          target_branch: readme-trophy_output
          build_dir: profile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
