name: TryHackMe Update Badge

on:
  # allows to manually run the job at any time
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  tryhackme-badge-update:
    name: Update TryHackMe badge
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Prepare output directory
        run: mkdir -p badge
        
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "BharatYadav007"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      # Push the generated PNG to the output branch
      - name: push thm_propic.png to the output branch
        uses: crazy-max/ghaction-github-pages@v5.0.0
        with:
          target_branch: tryhackme-badge_output
          build_dir: badge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
